
from enum import IntEnum


# Key codes from glfw.__init__.py
class MouseCode(IntEnum):
    MOUSE_BUTTON_1 = 0
    MOUSE_BUTTON_2 = 1
    MOUSE_BUTTON_3 = 2
    MOUSE_BUTTON_4 = 3
    MOUSE_BUTTON_5 = 4
    MOUSE_BUTTON_6 = 5
    MOUSE_BUTTON_7 = 6
    MOUSE_BUTTON_8 = 7
    MOUSE_BUTTON_LAST = MOUSE_BUTTON_8
    MOUSE_BUTTON_LEFT = MOUSE_BUTTON_1
    MOUSE_BUTTON_RIGHT = MOUSE_BUTTON_2
    MOUSE_BUTTON_MIDDLE = MOUSE_BUTTON_3


HZ_MOUSE_BUTTON_1 = MouseCode.MOUSE_BUTTON_1
HZ_MOUSE_BUTTON_2 = MouseCode.MOUSE_BUTTON_2
HZ_MOUSE_BUTTON_3 = MouseCode.MOUSE_BUTTON_3
HZ_MOUSE_BUTTON_4 = MouseCode.MOUSE_BUTTON_4
HZ_MOUSE_BUTTON_5 = MouseCode.MOUSE_BUTTON_5
HZ_MOUSE_BUTTON_6 = MouseCode.MOUSE_BUTTON_6
HZ_MOUSE_BUTTON_7 = MouseCode.MOUSE_BUTTON_7
HZ_MOUSE_BUTTON_8 = MouseCode.MOUSE_BUTTON_8
HZ_MOUSE_BUTTON_LAST = MouseCode.MOUSE_BUTTON_LAST
HZ_MOUSE_BUTTON_LEFT = MouseCode.MOUSE_BUTTON_1
HZ_MOUSE_BUTTON_RIGHT = MouseCode.MOUSE_BUTTON_2
HZ_MOUSE_BUTTON_MIDDLE = MouseCode.MOUSE_BUTTON_3
